### ISSUE TITLE
[FEAT] iOS 2차 과제

### ISSUE THREAD

**Issue by meenyweeny** [29th-WE-SOPT-iOS-Part/LeeGyeongMin#4]
## 📌  Feature Issue

AutoLayout으로 UI 구성하기
화면 전환
데이터 전달
Tabbar 만들기

## 📝  To-do

- [ ] AutoLayout으로 UI 구성하기
- [ ] ViewController에서 ViewController로 화면 전환하기
- [ ] 마지막 ViewController에서 첫 ViewController로 화면 전환하기
- [ ] ViewController에서 TabbarController로 화면 전환하기 (Present)
- [ ] ViewController에서 Data 전달해서 이름 띄우기
- [ ] Tabbar 코드로 구현
