### ISSUE TITLE
[FEAT] iOS 3차 과제

### ISSUE THREAD

**Issue by meenyweeny** [29th-WE-SOPT-iOS-Part/LeeGyeongMin#6]
## 📌  Feature Issue
2주차 과제에서 했던 Tabbar의 Home ViewController에
TableView, CollectionView, UIView 구성하기
+ 도전과제 (내용의 크기에 따라 cell의 크기가 달라지게 하는 기능 구현하기)

## 📝  To-do
- [x] TableView Cell Autolayout
- [x] TableView Cell DataModel 파일 만들고 data 입력
- [x] CollectionView Cell Autolayout
- [x] CollectionView Cell DataModel 파일 만들고 data 입력
- [x] UIView 맨 위에 구성하기
- [ ] 도전과제
