### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by meenyweeny** [29th-WE-SOPT-iOS-Part/LeeGyeongMin#9]
## 📌  Feature Issue

로그인, 회원가입 창에서 서버 연결하기

## 📝  To-do

- [x] profile 누르면 Login 화면으로의 전환
- [x] youtube home 화면이 첫 화면으로 보이게 변경
- [x] 로그인 화면에서의 서버통신 및 alert 창 띄우기
- [x] 회원가입 화면에서의 서버통신 및 alert 창 띄우기

도전과제
- [x] userDefaults 활용하기
